### ISSUE TITLE
[Enhancement] Freemoji: Detect no external emojis perms

### ISSUE THREAD

**Issue by dav1312** [QbDesu/BetterDiscordAddons#2]
Enable all emojis even when external emojis perms is disabled.
To avoid having to change servers to take the link so send it in the original server.

**Comment by QbDesu** [comment]
I thought about adding this in part because I knew this request would come sooner or later, even if I didn't expect it before the release. The thing about it is, I kinda wanna respect the server admins decision to not allow external emotes.

If I add this it will definitely be disabled by default for the above reason, I can say this much.

**Comment by QbDesu** [comment]
![image](https://user-images.githubusercontent.com/5641607/126085974-abb6d74c-b2ee-480c-940b-92fd5fa114d1.png)
this is unfortunately inside a deeply nested function so it may take a while till I actually do this. Might be as simple as patching the `getEmojiUnavailableReason` method to return another reason but that's for another today.

**Comment by QbDesu** [comment]
implemented in https://github.com/QbDesu/BetterDiscordAddons/commit/2de634e5a82d8d92bb743ffe162da122c51245a9
Same as last time. I would appreciate some more testing before closing this. Close if you feel like it's working correctly.

**Comment by QbDesu** [comment]
You never ended up closing this D:
Anyway, plugin discontinued. May work on it a little more for personal use when it breaks. Hmu when that happens and you want a fixed version.
