### ISSUE TITLE
✨Freemoji Stickers✨

### ISSUE THREAD

**Issue by akippnn** [QbDesu/BetterDiscordAddons#38]
**Is your feature request related to a problem? Please describe.**
Freemojis let us use emojis from other servers with links, and it works really well than its predecessor. However, it doesn't support Stickers.

**Describe the solution you'd like**
Support Stickers.

**Describe alternatives you've considered**
I tried using Free Stickers but whenever I go to Stickers, it crashes the client.

**Additional context**
[Free Stickers](https://github.com/An00nymushun/DiscordFreeStickers)

**Comment by Obazzi** [comment]
>  I tried using Free Stickers but whenever I go to Stickers, it crashes the client.

Have you reported this to the Free Stickers devs by opening an issue there?

**Comment by Obazzi** [comment]
The problem with stickers is animated stickers is that we can't just send a link to the sticker like the Freemoji plugin dose for Emojis because animated stickers are in APNG format and Discord does not animate APNG images. I assume the Free Stickers plugin actually has to convert the Stickers to a GIF before sending.

The plugin could always just send the link to the image and oh well if the animated stickers don't animate, but if Free Stickers exist and your issue can be fixed by informing the developers of the crash, then I don't see the point of this.

**Comment by SmolAlli** [comment]
AFAIK there was a stickers plugin but it got taken down shortly after it was added to the BD website due to Discord saying they'll ban users who send stickers as links (at least that's the explanation I got)
Edit: this applies only to Discord's default stickers, it appears.

**Comment by Obazzi** [comment]
> AFAIK there was a stickers plugin but it got taken down shortly after it was added to the BD website due to Discord saying they'll ban users who send stickers as links (at least that's the explanation I got)

Anyone can send a stickers link, all you need is the developers tools that are built in all web browsers and then find the link to the sticker and then send it. Is that truly against TOS? They would ban people sending some links with no prior warning? Do you have any proof about this? Because, If this is actually true and not fearmongering, I will alert this sticker plugin project https://github.com/An00nymushun/DiscordFreeStickers and tell them they should add a disclaimer to their README.

**Comment by QbDesu** [comment]
Sticker support was not something I wanted to pursue. The plugin is also discontinued now.
