### ISSUE TITLE
BetterBotTags Broken

### ISSUE THREAD

**Issue by rollingmoai** [QbDesu/BetterDiscordAddons#44]
**Describe the bug**
```js
BetterBotTags: Could not be constructed.
at Object.initializeAddon (<anonymous>:4:306918)
at Object.loadAddon (<anonymous>:4:268405)
at Object.loadAddon (<anonymous>:4:305956)
at FSWatcher.<anonymous> (<anonymous>:4:266254)
```
**To Reproduce**
1. Install plugin
2. See error.

**Expected behavior**
It works.

**Details (please complete the following information):**
 - Addon Name: BetterBotTags 
 - Discord Release Channel: Stable

**Comment by sertdfyguhi** [comment]
i agree

**Comment by QuentinMcCarthy** [comment]
Same, does not compile

**Comment by ApexModder** [comment]
Same plugin fails to be constructed on start up every time
<details>
<summary>Console exception</summary>

![image](https://user-images.githubusercontent.com/29412632/161369404-46dbd28a-85fa-483c-94d3-fdfb9fa8aba4.png)
</details>

**Comment by QbDesu** [comment]
Fixed in v.1.1.0. The plugin needs to be redownloaded from Github (takes a while for the update to be verified on the official website) Also fixes the jankiness with the Webhook icon
Ctrl+S/Right-Click -> Save As... https://raw.githubusercontent.com/QbDesu/BetterDiscordAddons/potato/Plugins/BetterBotTags/BetterBotTags.plugin.js
