### ISSUE TITLE
[Bug] Freemoji: Link doesn't appear for disabled "boost emojis"

### ISSUE THREAD

**Issue by dav1312** [QbDesu/BetterDiscordAddons#5]
**Describe the bug**
For emojis that are disabled due to the server not having enough boosts the link doesn't appear.

**To Reproduce**
1. Join a server that has emojis disabled due to not having enough boosts
2. Click a disabled emoji

**Expected behavior**
The link should appear

**Details (please complete the following information):**
 - Addon Name: Freemoji
 - Addon Version: 1.2.0
 - Discord Release Channel: Stable

**Comment by QbDesu** [comment]
I need to get onto a server with that to test why. >.<'

**Comment by dav1312** [comment]
> I need to get onto a server with that to test why. >.<'

@QbDesu https://discord.gg/NCzM9WM

**Comment by QbDesu** [comment]
fixed in, https://github.com/QbDesu/BetterDiscordAddons/commit/172fbfb695799ff47bf129b8c14211cd0ccdde87
I would appreciate some more testing though. Close if you feel like it's working correctly.

This was a feature by the way. An0 seems to have had an explicit check in it to check if the emoji is unavailable. While there is some slight adjustments needed other than removing the check but they could have easily implemented it if they wanted to.

**Comment by SeasonalFerret** [comment]
Just had this issue.
I have nitro, but I attempted to use a boost lvl 1 emoji from another server, it wouldn't post the image and I couldn't use the emoji because the boost ran out. 
Ended up just boosting the server myself so I can't test for a fix, but shucks, I had hoped this would fix it.
