### ISSUE TITLE
Changing the emoji "format" in Freemoji plugin

### ISSUE THREAD

**Issue by cRu572Vltn** [QbDesu/BetterDiscordAddons#51]
I've been using free emoji apps for a while now, and never had any major problems until a couple of months ago, with this plugin. I'm not saying it's something serious, but it's something... weird, at least for me.

I don't know the reason why this was done, but, is it really necessary to add "loseless" in the embed links and force it to be in webp format? In my case, it changes absolutely nothing and actually worsens the quality of the emoji.
After a couple of tests, the png format is still the one that gives the best image quality... With webp it's as if a smoothing was applied that simply deteriorates the way it looks in my opinion.
My idea is that if possible, in a future update, an option to configure these parameters should be added?
I don't know if this is intentional for some reason **(if it is the case I would have no problem to understand the reason behind it)**, but at least for me, it worked better the old way, png and without anything weird added to the link.

**Comment by QbDesu** [comment]
Am option to use png instead of webp was added to Freemoji in the last update. The change you experienced was because Discord themselves migrated to use webp in most cases, emoji for them are also just images after all. this also includes the "lossless" parameter, it is now in the emoji's standard url's standard url path. All the plugin did was add a size parameter to it. An option to remove the lossless parameter won't be added as the plugin was discontinued in the mean time.
